[package]
name = "isometric"
version = "0.1.0"
authors = ["Thomas Elder <tgelder@gmail.com>"]

[dependencies]
bincode = "1.3"
gl = "0.14"
glutin = "0.19.0"
commons = { path = "../commons" }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
x11-dl = "2.18.5"