[package]
name = "commons"
version = "0.1.0"
authors = ["Thomas Elder <tgelder@gmail.com>"]

[dependencies]
image = "0.21.0"
nalgebra = { version = "0.17.2", features = ["serde-serialize"] }
num = "0.2"
rand = "0.6"
serde = { version = "1.0", features = ["derive"] }
