[package]
name = "frontier"
version = "0.1.0"
authors = ["Thomas Elder <tgelder@gmail.com>"]
edition = "2018"

[dependencies]
commons = { path = "../commons" }
isometric = { path = "../isometric" }
pioneer = { path = "../pioneer" }
network = { path = "../network" }
nalgebra = { version = "0.17.2", features = ["serde-serialize"] }
image = "0.21.0"
rand = "0.6"
line_drawing = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.4"