[package]
name = "frontier"
version = "0.1.0"
authors = ["Thomas Elder <tgelder@gmail.com>"]
edition = "2018"

[dependencies]
isometric = { path = "../isometric" }
pioneer = { path = "../pioneer" }
nalgebra = "0.17.2"
image = "0.21.0"