[package]
name = "frontier"
version = "0.1.0"
authors = ["Thomas Elder <tgelder@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.1"
commons = { path = "../commons" }
futures = { version = "0.3", features = ["thread-pool"] }
isometric = { path = "../isometric" }
pioneer = { path = "../pioneer" }
network = { path = "../network" }
line_drawing = "0.7.0"
serde = { version = "1.0", features = ["derive"] }