[package]
name = "frontier"
version = "0.1.0"
authors = ["Thomas Elder <tgelder@gmail.com>"]
edition = "2018"

[dependencies]
commons = { path = "../commons" }
isometric = { path = "../isometric" }
pioneer = { path = "../pioneer" }
network = { path = "../network" }
nalgebra = "0.17.2"
image = "0.21.0"
rand = "0.6"